# Generated by Django 4.0.1 on 2022-03-19 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=500)),
                ('taxi_number', models.CharField(blank=True, default='', max_length=500)),
                ('balance', models.IntegerField(blank=True, default=0)),
                ('is_charged_today', models.BooleanField(default=False)),
                ('last_charged_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
