# Generated by Django 4.0.1 on 2022-03-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivertable',
            name='last_charged_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
