# Generated by Django 4.0.1 on 2022-03-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_rename_is_charged_today_drivertable_is_paid_today_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertable',
            name='stamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
