# Generated by Django 4.0.1 on 2022-03-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_drivertable_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertable',
            name='owed',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
