# Generated by Django 4.0.1 on 2022-03-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_drivertable_owed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivertable',
            name='balance',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
