# Generated by Django 4.0.1 on 2022-03-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_alter_drivertable_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivertable',
            name='last_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivertable',
            name='last_rent_deduction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
