# Generated by Django 4.0.1 on 2022-03-20 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_alter_drivertable_last_paid_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivertable',
            name='last_paid_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='drivertable',
            name='last_rent_deduction_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
