# Generated by Django 4.0.1 on 2022-03-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_alter_drivertable_last_paid_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivertable',
            name='stamp',
        ),
    ]
