# Generated by Django 4.0.1 on 2022-03-31 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('root', '0010_remove_drivertable_stamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxi_number', models.CharField(blank=True, default='', max_length=500)),
                ('balance', models.FloatField(blank=True, default=0)),
                ('owed', models.FloatField(blank=True, default=0)),
                ('is_rent_deducted_today', models.BooleanField(default=False)),
                ('is_paid_today', models.BooleanField(default=False)),
                ('last_rent_deduction_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('last_paid_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DriverTable',
        ),
    ]
