# Generated by Django 4.0.1 on 2022-03-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_profile_delete_drivertable'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auth_code',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
