# Generated by Django 4.0.1 on 2022-03-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0013_profile_password_reset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
