# Generated by Django 4.0.1 on 2022-04-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0014_profile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='temp_owed',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
